package com.situ.aichat.ui.liuli.diary

import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.ui.test.assertCountEquals
import androidx.compose.ui.test.getUnclippedBoundsInRoot
import androidx.compose.ui.test.hasScrollToIndexAction
import androidx.compose.ui.test.hasText
import androidx.compose.ui.test.junit4.v2.createComposeRule
import androidx.compose.ui.test.longClick
import androidx.compose.ui.test.onAllNodesWithContentDescription
import androidx.compose.ui.test.onAllNodesWithText
import androidx.compose.ui.test.onNodeWithContentDescription
import androidx.compose.ui.test.onNodeWithText
import androidx.compose.ui.test.performClick
import androidx.compose.ui.test.performScrollToNode
import androidx.compose.ui.test.performTouchInput
import com.situ.aichat.data.local.entity.CharacterEntity
import com.situ.aichat.data.local.entity.DiaryEntryEntity
import com.situ.aichat.data.local.entity.DiaryEntryWithComments
import com.situ.aichat.data.model.AppSkin
import com.situ.aichat.prompt.diary.DiaryExchangeService
import com.situ.aichat.ui.components.AppHaptics
import com.situ.aichat.ui.components.LocalAppHaptics
import com.situ.aichat.ui.diary.DiaryEntryFilter
import com.situ.aichat.ui.diary.DiaryExchangeUiState
import com.situ.aichat.ui.diary.DiaryViewMode
import com.situ.aichat.ui.theme.AIPocketChatTheme
import io.mockk.mockk
import org.junit.Assert.assertEquals
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import java.time.YearMonth
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import java.util.Locale

/**
 * T2-L1–L9（琉璃 2.0 卷六·一 §4.1）：直接驱动无 VM 的 [LiuliDiaryListPage]——空态 / 筛选 / 连续天数 / 横幅 / 情境卡门控 /
 * 卡片三种手势 / 视图菜单 / 日历 / 大标题与筛选条的收起。期望从暖陶行为与图纸几何独立反推（Robolectric 状态栏恒 0）。
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34], qualifiers = "zh-rCN-w411dp-h891dp")
class LiuliDiaryListPageTest {

    @get:Rule
    val compose = createComposeRule()

    private val now = System.currentTimeMillis()
    private val day = 86_400_000L
    private val xiaoman = CharacterEntity(uuid = "xm", name = "小满", creationDate = now)

    private val composes = mutableListOf<String>()
    private val opened = mutableListOf<String>()
    private val longPressed = mutableListOf<String>()
    private val published = mutableListOf<String>()
    private val modes = mutableListOf<DiaryViewMode>()
    private var statsShown = 0

    private fun ewc(entry: DiaryEntryEntity) = DiaryEntryWithComments(entry = entry, comments = emptyList())

    private val mine = ewc(DiaryEntryEntity(uuid = "m1", content = "今天风很大伞差点飞走", timestamp = now - 3_600_000, moodEmoji = "😌"))
    private val letter = ewc(
        DiaryEntryEntity(
            uuid = "l1", content = "小满写给你的一封信", timestamp = now - day,
            isAutoGenerated = true, authorCharacterUuid = "xm", authorNameSnapshot = "小满",
        ),
    )
    private val draft = ewc(DiaryEntryEntity(uuid = "d1", content = "一篇还没发的草稿", timestamp = now - 2 * day, isDraft = true))

    private fun data(
        entries: List<DiaryEntryWithComments> = emptyList(),
        apiMissing: Boolean = false,
        streak: Int = 0,
        exchange: DiaryExchangeUiState = DiaryExchangeUiState(),
        onThisDay: List<DiaryEntryWithComments> = emptyList(),
    ) = LiuliDiaryListData(
        entries = entries,
        apiMissing = apiMissing,
        charactersByUuid = mapOf(xiaoman.uuid to xiaoman),
        exchangeUi = exchange,
        justUnlockedUuid = null,
        streakDays = streak,
        onThisDay = onThisDay,
        monthlyReviews = emptyMap(),
        reviewGeneratingMonth = null,
        reviewFailedMonth = null,
    )

    private val callbacks = LiuliDiaryListCallbacks(
        onBack = {},
        onCompose = { composes += "compose" },
        onOpenEntry = { opened += it },
        onPublish = { published += it },
        onUnlock = {},
        onOpenReview = {},
        onGenerateReview = {},
        onShowStats = { statsShown++ },
        onLongPress = { longPressed += it },
    )

    private fun show(d: LiuliDiaryListData, viewMode: DiaryViewMode = DiaryViewMode.TIMELINE, initialFilter: DiaryEntryFilter = DiaryEntryFilter.ALL) {
        compose.setContent {
            var filter by mutableStateOf(initialFilter)
            AIPocketChatTheme(darkTheme = false, skin = AppSkin.LIULI) {
                CompositionLocalProvider(LocalAppHaptics provides mockk<AppHaptics>(relaxed = true)) {
                    LiuliDiaryListPage(
                        data = d,
                        callbacks = callbacks,
                        viewMode = viewMode,
                        onViewModeChange = { modes += it },
                        entryFilter = filter,
                        onFilterChange = { filter = it },
                    )
                }
            }
        }
        compose.waitForIdle()
    }

    @Test fun L1_空日记本出空态且两个入口都去写() {
        show(data())
        compose.onNodeWithText("还没有日记").assertExists()
        compose.onAllNodesWithText("全部").assertCountEquals(0)
        compose.onNodeWithText("写日记").performClick()
        compose.onNodeWithText("写一笔").performClick()
        compose.waitForIdle()
        assertEquals(2, composes.size)
    }

    @Test fun L2_筛到TA的信只剩信且信封消失() {
        show(data(entries = listOf(mine, letter, draft), exchange = DiaryExchangeUiState(DiaryExchangeService.State.NeedPublish("小满"))))
        compose.onNodeWithText("去写日记").assertExists()
        compose.onNodeWithText("TA 的信").performClick()
        compose.waitForIdle()
        compose.onAllNodesWithText("小满写给你的一封信", substring = true).assertCountEquals(1)
        compose.onAllNodesWithText("今天风很大伞差点飞走", substring = true).assertCountEquals(0)
        compose.onAllNodesWithText("一篇还没发的草稿", substring = true).assertCountEquals(0)
        compose.onAllNodesWithText("去写日记").assertCountEquals(0)
    }

    @Test fun L3_连续天数零不出五出() {
        show(data(entries = listOf(mine), streak = 0))
        compose.onAllNodesWithContentDescription("连续记录", substring = true).assertCountEquals(0)
    }

    @Test fun L3_连续五天读屏念连续记录5天() {
        show(data(entries = listOf(mine), streak = 5))
        compose.onNodeWithContentDescription("连续记录 5 天").assertExists()
    }

    @Test fun L4_未配API横幅在() {
        show(data(entries = listOf(mine), apiMissing = true))
        compose.onNodeWithText("自动日记因未配置 API 暂停").assertExists()
    }

    @Test fun L5_只有全部才出那年今天() {
        val yearAgo = ewc(DiaryEntryEntity(uuid = "y1", content = "去年今天的日记", timestamp = now - 365 * day))
        show(data(entries = listOf(mine), onThisDay = listOf(yearAgo)))
        compose.onNodeWithText("那年今天").assertExists()
        compose.onNodeWithText("我的").performClick()
        compose.waitForIdle()
        compose.onAllNodesWithText("那年今天").assertCountEquals(0)
    }

    @Test fun L6_长按删单击开草稿可发布() {
        show(data(entries = listOf(mine, letter, draft)))
        compose.onNodeWithText("今天风很大伞差点飞走", substring = true).performTouchInput { longClick() }
        compose.waitForIdle()
        assertEquals(listOf("m1"), longPressed)
        compose.onNodeWithText("今天风很大伞差点飞走", substring = true).performClick()
        compose.waitForIdle()
        assertEquals(listOf("m1"), opened)
        compose.onNodeWithText("发布").performClick()
        compose.waitForIdle()
        assertEquals(listOf("d1"), published)
    }

    @Test fun L7_视图菜单三模式加回顾与统计() {
        show(data(entries = listOf(mine)))
        compose.onNodeWithContentDescription("视图模式").performClick()
        compose.waitForIdle()
        listOf("时间线", "列表", "日历", "回顾与统计").forEach { compose.onNodeWithText(it).assertExists() }
        compose.onNodeWithText("列表").performClick()
        compose.waitForIdle()
        assertEquals(listOf(DiaryViewMode.LIST), modes)
        compose.onNodeWithContentDescription("视图模式").performClick()
        compose.waitForIdle()
        compose.onNodeWithText("回顾与统计").performClick()
        compose.waitForIdle()
        assertEquals(1, statsShown)
    }

    @Test fun L8_日历视图出本月标题与今天的日记() {
        val today = ewc(DiaryEntryEntity(uuid = "t1", content = "今天的一篇", timestamp = now))
        show(data(entries = listOf(today)), viewMode = DiaryViewMode.CALENDAR)
        val zone = ZoneId.systemDefault()
        val monthTitle = YearMonth.now(zone).atDay(1).format(DateTimeFormatter.ofPattern("yyyy年M月", Locale.getDefault()))
        compose.onNodeWithText(monthTitle).assertExists()
        compose.onNodeWithText("今天的一篇", substring = true).assertExists()
    }

    @Test fun L9_静止时筛选条在大标题下收起后住进胶囊() {
        val twenty = (0 until 20).map { i ->
            ewc(DiaryEntryEntity(uuid = "e$i", content = "第${i}篇日记正文", timestamp = now - i * day))
        }
        show(data(entries = twenty))
        // 纸面筛选条 36 高：条顶 = 导航行 44 + 标题带 42 + 条上内距 12 = 98 → 段中线 = 98 + 18。
        compose.onAllNodesWithText("全部").assertCountEquals(1)
        val resting = compose.onNodeWithText("全部").getUnclippedBoundsInRoot()
        assertEquals(98f, ((resting.top + resting.bottom) / 2).value - 18f, 1f)

        compose.onNode(hasScrollToIndexAction()).performScrollToNode(hasText("第19篇日记正文", substring = true))
        compose.waitForIdle()
        // 玻璃筛选条 40 高：条顶 = 胶囊 44 + subBar 上内距 8 = 52 → 段中线 = 52 + 20。
        compose.onAllNodesWithText("全部").assertCountEquals(1)
        val collapsed = compose.onNodeWithText("全部").getUnclippedBoundsInRoot()
        assertEquals(52f, ((collapsed.top + collapsed.bottom) / 2).value - 20f, 1f)
    }
}
