package com.situ.aichat.ui.liuli.diary

import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.ui.test.assertCountEquals
import androidx.compose.ui.test.hasSetTextAction
import androidx.compose.ui.test.junit4.v2.createComposeRule
import androidx.compose.ui.test.longClick
import androidx.compose.ui.test.onAllNodesWithContentDescription
import androidx.compose.ui.test.onAllNodesWithText
import androidx.compose.ui.test.onNodeWithContentDescription
import androidx.compose.ui.test.onNodeWithText
import androidx.compose.ui.test.performClick
import androidx.compose.ui.test.performScrollTo
import androidx.compose.ui.test.performTextInput
import androidx.compose.ui.test.performTouchInput
import com.situ.aichat.data.local.entity.CharacterEntity
import com.situ.aichat.data.local.entity.DiaryCommentEntity
import com.situ.aichat.data.local.entity.DiaryEntryEntity
import com.situ.aichat.data.local.entity.DiaryEntryWithComments
import com.situ.aichat.data.model.AppSkin
import com.situ.aichat.ui.components.AppHaptics
import com.situ.aichat.ui.components.LocalAppHaptics
import com.situ.aichat.ui.theme.AIPocketChatTheme
import io.mockk.mockk
import org.junit.Assert.assertEquals
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/**
 * T2-D1–D7（琉璃 2.0 卷六·一 §4.3）：直接驱动无 VM 的 [LiuliDiaryDetailPage]——空条目 / 两种落款 / 故友来信 /
 * 行内回复 / 留言门控 / 删评论 / 更多菜单。规格 = 暖陶详情页行为（§2.3-7）。
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34], qualifiers = "zh-rCN-w411dp-h891dp")
class LiuliDiaryDetailPageTest {

    @get:Rule
    val compose = createComposeRule()

    private val now = System.currentTimeMillis()
    private val xiaoman = CharacterEntity(uuid = "xm", name = "小满", creationDate = now)
    private val chars = mapOf(xiaoman.uuid to xiaoman)

    private val edits = mutableListOf<String>()
    private var deleteRequests = 0
    private val deletedComments = mutableListOf<String>()
    private val replies = mutableListOf<Pair<String, String>>()
    private val notes = mutableListOf<String>()

    private val mine = DiaryEntryEntity(uuid = "m1", content = "今天风很大", timestamp = now - 3_600_000)
    private val letter = DiaryEntryEntity(
        uuid = "l1", content = "他今天说风好大", timestamp = now - 7_200_000,
        isAutoGenerated = true, authorCharacterUuid = "xm", authorNameSnapshot = "小满",
    )

    private fun comment(id: String, fromUser: Boolean, parent: String? = null, content: String = id) = DiaryCommentEntity(
        id = id, entryUuid = "e", content = content, timestamp = now - 600_000,
        characterUuid = if (fromUser) null else "xm", parentCommentId = parent, isFromUser = fromUser,
    )

    private fun show(ewc: DiaryEntryWithComments?, characters: Map<String, CharacterEntity> = chars) {
        compose.setContent {
            AIPocketChatTheme(darkTheme = false, skin = AppSkin.LIULI) {
                CompositionLocalProvider(LocalAppHaptics provides mockk<AppHaptics>(relaxed = true)) {
                    LiuliDiaryDetailPage(
                        entryWithComments = ewc,
                        charactersByUuid = characters,
                        onBack = {},
                        onEdit = { edits += it },
                        onRequestDelete = { deleteRequests++ },
                        onDeleteComment = { deletedComments += it },
                        onReply = { root, text -> replies += root to text },
                        onSendNote = { notes += it },
                    )
                }
            }
        }
        compose.waitForIdle()
    }

    @Test fun D1_条目为空时空白页无更多() {
        show(null)
        compose.onAllNodesWithContentDescription("更多").assertCountEquals(0)
    }

    @Test fun D2_自己的日记落款记于() {
        show(DiaryEntryWithComments(mine, emptyList()))
        compose.onNodeWithText("记于", substring = true).assertExists()
        compose.onAllNodesWithText("——", substring = true).assertCountEquals(0)
    }

    @Test fun D3_TA的信署名与故友淡标() {
        show(DiaryEntryWithComments(letter, emptyList()))
        compose.onNodeWithText("—— 小满 · 写于", substring = true).assertExists()
        compose.onAllNodesWithText("记于", substring = true).assertCountEquals(0)
        compose.onAllNodesWithText("故友的信").assertCountEquals(0)
    }

    @Test fun D3_作者已删出故友淡标且署快照名() {
        show(DiaryEntryWithComments(letter.copy(authorNameSnapshot = "旧名小满"), emptyList()), characters = emptyMap())
        compose.onNodeWithText("故友的信").assertExists()
        compose.onNodeWithText("—— 旧名小满 · 写于", substring = true).assertExists()
    }

    @Test fun D4_回复一轮() {
        show(DiaryEntryWithComments(mine, listOf(comment("root", fromUser = false, content = "两个蛋给我也来一碗"))))
        compose.onNodeWithText("回复").performScrollTo().performClick()
        compose.waitForIdle()
        compose.onNode(hasSetTextAction()).performTextInput("好呀")
        compose.onNodeWithText("发送").performClick()
        compose.waitForIdle()
        assertEquals(listOf("root" to "好呀"), replies)
    }

    @Test fun D5_交换信无用户顶层留言才有留言入口() {
        show(DiaryEntryWithComments(letter, emptyList()))
        compose.onNodeWithText("给 TA 留言").assertExists()
    }

    @Test fun D5_已有用户顶层留言则无留言入口() {
        show(DiaryEntryWithComments(letter, listOf(comment("note", fromUser = true, content = "我也想你"))))
        compose.onAllNodesWithText("给 TA 留言").assertCountEquals(0)
    }

    @Test fun D6_长按评论删评论() {
        show(DiaryEntryWithComments(mine, listOf(comment("c1", fromUser = false, content = "两个蛋给我也来一碗"))))
        compose.onNodeWithText("两个蛋给我也来一碗", substring = true).performScrollTo().performTouchInput { longClick() }
        compose.waitForIdle()
        compose.onNodeWithText("删除评论").performClick()
        compose.waitForIdle()
        compose.onNodeWithText("删除").performClick()
        compose.waitForIdle()
        assertEquals(listOf("c1"), deletedComments)
    }

    @Test fun D7_更多菜单编辑与删除() {
        show(DiaryEntryWithComments(mine, emptyList()))
        compose.onNodeWithContentDescription("更多").performClick()
        compose.waitForIdle()
        compose.onNodeWithText("编辑").performClick()
        compose.waitForIdle()
        assertEquals(listOf("m1"), edits)
        compose.onNodeWithContentDescription("更多").performClick()
        compose.waitForIdle()
        compose.onNodeWithText("删除").performClick()
        compose.waitForIdle()
        assertEquals(1, deleteRequests)
    }
}
