package com.situ.aichat

import androidx.room.testing.MigrationTestHelper
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.situ.aichat.data.local.AppDatabase
import com.situ.aichat.data.local.MIGRATION_49_50
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

/**
 * T3-1（朋友圈发布页重构·甲 §7·E17）：v49 插一条旧动态 → 迁到 v50 → ①旧行一字不变、行不丢；
 * ②新列 `mentionedCharacterUuidsJson` 落 ''（= 没提醒任何人）；③可写可读回。
 * 种子 INSERT 列清单 = 49.json `moment_post` 里「NOT NULL 且无 SQL DEFAULT」的全部 8 列 + `characterUuid` NULL
 * （脚本从 49.json 机器推导·PITFALLS §1a）。逐版本全链校验仍由 [MigrationTest]（LATEST_VERSION = 50）负责。
 */
@RunWith(AndroidJUnit4::class)
class MomentMentionMigrationTest {

    @get:Rule
    val helper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        AppDatabase::class.java,
    )

    @Test
    fun migration49To50AddsMentionColumnKeepingOldRows() {
        helper.createDatabase(TEST_DB, 49).apply {
            execSQL(
                "INSERT INTO moment_post (" +
                    "uuid, content, timestamp, authorTypeRaw, characterUuid, isAutoGenerated, imagePathsJson, isSoftDeleted, triggerTypeRaw" +
                    ") VALUES (" +
                    "'post-1', '今天风很好', 1756800000000, 'user', NULL, 0, '[\"/img/a.jpg\"]', 0, 'auto_draft'" +
                    ")",
            )
            close()
        }

        helper.runMigrationsAndValidate(TEST_DB, 50, true, MIGRATION_49_50).use { db ->
            db.query(
                "SELECT content, timestamp, authorTypeRaw, characterUuid IS NULL, isAutoGenerated, imagePathsJson, " +
                    "isSoftDeleted, triggerTypeRaw, relatedGiftId IS NULL, mentionedCharacterUuidsJson " +
                    "FROM moment_post WHERE uuid = 'post-1'",
            ).use { c ->
                assertTrue("旧动态行必须还在", c.moveToFirst())
                assertEquals("今天风很好", c.getString(0))
                assertEquals(1756800000000L, c.getLong(1))
                assertEquals("user", c.getString(2))
                assertEquals(1, c.getInt(3))
                assertEquals(0, c.getInt(4))
                assertEquals("[\"/img/a.jpg\"]", c.getString(5))
                assertEquals(0, c.getInt(6))
                assertEquals("auto_draft", c.getString(7))
                assertEquals(1, c.getInt(8))
                assertEquals("新列落空串 = 没提醒任何人", "", c.getString(9))
            }
            db.query("SELECT COUNT(*) FROM moment_post").use { c ->
                assertTrue(c.moveToFirst())
                assertEquals("行数不变", 1, c.getInt(0))
            }
            db.execSQL("UPDATE moment_post SET mentionedCharacterUuidsJson = '[\"c1\",\"c2\"]' WHERE uuid = 'post-1'")
            db.query("SELECT mentionedCharacterUuidsJson FROM moment_post WHERE uuid = 'post-1'").use { c ->
                assertTrue(c.moveToFirst())
                assertEquals("[\"c1\",\"c2\"]", c.getString(0))
            }
        }
    }

    private companion object {
        const val TEST_DB = "moment-mention-migration-test.db"
    }
}
