package com.situ.aichat.ui.diary

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.text.selection.SelectionContainer
import androidx.compose.material3.Icon
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.drawBehind
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextIndent
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.em
import com.situ.aichat.R
import com.situ.aichat.data.local.entity.CharacterEntity
import com.situ.aichat.data.local.entity.DiaryCommentEntity
import com.situ.aichat.data.local.entity.DiaryEntryEntity
import com.situ.aichat.data.model.DiaryVisibility
import com.situ.aichat.ui.designsystem.AppTheme

// 日记详情的内容件（琉璃 2.0 卷六·一 §3.4：自 [DiaryDetailScreen] 只搬不改·两张脸共用；信笺材质由外面给）。

/** 正文段落间距（③ U2·呼吸感）。 */
internal val DiaryParagraphGap = 10.dp

/**
 * 正文渲染：③ 段落呼吸（[splitDiaryParagraphs] 分段 + 段间距 + 首行缩进两字·两方通用·U2③）；
 * ⑤ TA 的信（[isLetter]）垫暖信笺——柔米底（surface.sunken）+ 顶端 letterhead 细线（陶土 16%）·仅详情页（U2⑤）。
 * [letterSurface] = 信笺材质（琉璃 2.0 卷六·一「材质外给」：默认 = 暖陶柔米底，琉璃传稿纸）。
 */
@Composable
internal fun DiaryDetailBody(
    content: String,
    style: TextStyle,
    isLetter: Boolean,
    letterSurface: Modifier = Modifier.clip(AppTheme.shapes.medium).background(AppTheme.colors.surface.sunken),
) {
    val colors = AppTheme.colors
    val paragraphs = remember(content) { splitDiaryParagraphs(content) }
    val paraStyle = style.copy(textIndent = TextIndent(firstLine = 2.em))
    val body = @Composable {
        SelectionContainer {
            Column(verticalArrangement = Arrangement.spacedBy(DiaryParagraphGap)) {
                paragraphs.forEach { p ->
                    Text(p, style = paraStyle, color = colors.text.primary)
                }
            }
        }
    }
    if (!isLetter) {
        body()
        return
    }
    val letterhead = colors.accent.primary.copy(alpha = 0.16f)
    Box(
        modifier = Modifier
            .fillMaxWidth()
            .then(letterSurface)
            .drawBehind {
                val inset = 16.dp.toPx()
                drawLine(
                    color = letterhead,
                    start = Offset(inset, 0f),
                    end = Offset(size.width - inset, 0f),
                    strokeWidth = 1.dp.toPx(),
                )
            }
            .padding(18.dp),
    ) {
        body()
    }
}

/** 元信息行：草稿徽章 + AI 生成 + 可见性（洇染头外·secondary 可用）。 */
@Composable
internal fun DetailMetaRow(entry: DiaryEntryEntity, commentCount: Int) {
    val colors = AppTheme.colors
    Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(10.dp)) {
        if (entry.isDraft) DraftBadge()
        if (entry.isAutoGenerated) {
            Text(stringResource(R.string.diary_ai_generated), style = AppTheme.typography.caption, color = colors.accent.text)
        }
        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(3.dp)) {
            Icon(
                diaryVisibilityIcon(entry.visibilityRaw),
                contentDescription = null,
                modifier = Modifier.size(14.dp),
                tint = colors.text.secondary,
            )
            Text(
                stringResource(
                    if (DiaryVisibility.fromRaw(entry.visibilityRaw) == DiaryVisibility.PRIVATE) {
                        R.string.diary_visibility_private
                    } else {
                        R.string.diary_visibility_open
                    },
                ),
                style = AppTheme.typography.caption,
                color = colors.text.secondary,
            )
        }
        Spacer(Modifier.weight(1f))
        if (commentCount > 0) {
            Text(
                stringResource(R.string.diary_comments_header, commentCount),
                style = AppTheme.typography.caption,
                color = colors.text.secondary,
            )
        }
    }
}

/** 图片画廊（每行 3 张方图·非 lazy）。 */
@Composable
internal fun DiaryDetailImageGrid(images: List<String>) {
    Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
        images.chunked(3).forEach { rowImages ->
            Row(horizontalArrangement = Arrangement.spacedBy(4.dp), modifier = Modifier.fillMaxWidth()) {
                rowImages.forEach { path ->
                    DiaryThumbnail(path, modifier = Modifier.weight(1f).aspectRatio(1f), corner = 12.dp)
                }
                // 补齐不足 3 张的占位，保证最后一行图片不被拉伸。
                repeat(3 - rowImages.size) { Spacer(Modifier.weight(1f)) }
            }
        }
    }
}

/** 印章小字（右对齐）：TA 的信 = 楷体署名「—— 名 · 写于 HH:mm」；用户日记 = 「记于 HH:mm」。 */
@Composable
internal fun DiaryDetailSignature(authorDisplay: DiaryAuthorDisplay?, timestamp: Long) {
    val colors = AppTheme.colors
    if (authorDisplay != null) {
        Text(
            stringResource(
                R.string.diary_exchange_signed,
                authorDisplay.name,
                formatDiaryDate(timestamp, "HH:mm"),
            ),
            style = AppTheme.typography.kaiQuote,
            color = colors.accent.text,
            textAlign = TextAlign.End,
            modifier = Modifier.fillMaxWidth(),
        )
    } else {
        Text(
            stringResource(R.string.diary_written_at, formatDiaryDate(timestamp, "HH:mm")),
            style = AppTheme.typography.captionNumeric,
            color = colors.text.secondary,
            textAlign = TextAlign.End,
            modifier = Modifier.fillMaxWidth(),
        )
    }
}

/** 正文字形（契约 §1 手法4）：AI 代写或 TA 的信 = 楷体，自己写的 = 正文黑体。 */
@Composable
internal fun diaryDetailBodyStyle(entry: DiaryEntryEntity): TextStyle =
    if (entry.isAutoGenerated || entry.authorCharacterUuid != null) AppTheme.typography.kaiBody else AppTheme.typography.body

/** R6-1 留言入口的作者（纯函数·T1）：交换信 + 作者仍在 + 用户尚无顶层留言 → 作者；否则 null。 */
internal fun diaryExchangeNoteAuthor(
    entry: DiaryEntryEntity,
    comments: List<DiaryCommentEntity>,
    charactersByUuid: Map<String, CharacterEntity>,
): CharacterEntity? = entry.authorCharacterUuid?.let { charactersByUuid[it] }?.takeIf { canLeaveExchangeNote(comments) }
