package com.situ.aichat.data.local.entity

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Mirrors the iOS `MomentPost` @Model (Models/MomentPost.swift) — a 朋友圈 (M06) post authored by the
 * user or an AI character.
 *
 * Storage notes (Android adaptations):
 * - Images: iOS `imageDataArray: [Data]?` external storage → here JPEGs on disk via
 *   `ContentImageStore`, with their paths kept as a JSON list in [imagePathsJson] (decode via
 *   `MomentPostEntity.imagePaths`). No BLOBs in the DB — same convention as `DiaryEntryEntity`.
 * - Enums (`authorTypeRaw` / `triggerTypeRaw`) store the iOS rawValue strings; decode via
 *   [com.situ.aichat.data.model.MomentAuthorType] / [com.situ.aichat.data.model.MomentTriggerType].
 * - [isSoftDeleted]: posts are soft-deleted (hidden from the feed) and hard-deleted 30 days later by
 *   the cleanup pass (7.2.5). iOS names the column `isDeleted` via `@Attribute(originalName:)`; this
 *   fresh schema simply names it `isSoftDeleted`.
 *
 * [triggerTypeRaw] / [relatedGiftId] are kept so the gift branch (P9) drops in without a migration.
 * Deleting a post cascades to its comments + likes (FKs on those entities). iOS indexes
 * `[\.timestamp], [\.characterUUID]`.
 */
@Entity(
    tableName = "moment_post",
    indices = [Index("timestamp"), Index("characterUuid")],
)
data class MomentPostEntity(
    @PrimaryKey val uuid: String,
    val content: String = "",
    val timestamp: Long = System.currentTimeMillis(),

    /** iOS `authorTypeRaw`; "user"/"character". Decode via `MomentAuthorType.fromRaw`. */
    val authorTypeRaw: String = "user",
    /** Set when [authorTypeRaw] == "character": the authoring AI character's uuid. */
    val characterUuid: String? = null,

    val isAutoGenerated: Boolean = false,

    /** JSON list of absolute image file paths (see `MomentPostEntity.imagePaths`). "" = none. */
    val imagePathsJson: String = "",

    /** Soft-deleted: hidden from feed, hard-deleted after 30 days. iOS column `isDeleted`. */
    val isSoftDeleted: Boolean = false,

    /** iOS `triggerTypeRaw`; "auto_draft"/"gift_received"/"pet_shop_purchase". */
    val triggerTypeRaw: String = "auto_draft",
    /** When [triggerTypeRaw] == "gift_received": the related GiftRecord uuid (P9). */
    val relatedGiftId: String? = null,
    /**
     * 「提醒谁看」的角色 uuid 列表（JSON·解码用 `MomentPostEntity.mentionedCharacterUuids`）。"" = 没提醒任何人。
     * 只有用户帖会有；写者唯一 = 发布页 [com.situ.aichat.ui.moments.ComposeMomentViewModel.publish]。
     * 朋友圈发布页重构·甲（docs/handoff/2026-09-27-朋友圈发布页-甲-底子.md §3.1）。
     */
    val mentionedCharacterUuidsJson: String = "",
)
