package com.situ.aichat.ui.chat

import com.situ.aichat.data.model.AppSettings
import android.content.Context
import com.situ.aichat.data.local.entity.CharacterEntity
import com.situ.aichat.data.local.entity.ConversationEntity
import com.situ.aichat.data.local.entity.MessageEntity
import com.situ.aichat.data.repository.ConversationRepository
import com.situ.aichat.tts.TtsConfigurationRepository
import com.situ.aichat.tts.TtsService
import com.situ.aichat.tts.provider.MiniMaxVoiceTagsSettings
import com.situ.aichat.prompt.PromptBuilder.AssistantDeliveryMode
import com.situ.aichat.tts.TtsConfiguration
import com.situ.aichat.tts.TtsVoiceProfile
import com.situ.aichat.tts.provider.MiniMaxVoiceTagsCapability
import kotlin.random.Random

/** Why a reply was planned as voice/text (1:1 iOS `AssistantDeliveryReason`). */
enum class AssistantDeliveryReason { USER_VOICE_MIRRORING, SCHEDULED_VOICE, TEXT }

/** A chat reply's voice/text plan, computed before the LLM call (1:1 iOS `AssistantDeliveryPlan`). */
data class AssistantDeliveryPlan(
    val mode: AssistantDeliveryMode,
    val reason: AssistantDeliveryReason,
) {
    val isVoice: Boolean get() = mode == AssistantDeliveryMode.VOICE
}

/** Post-delivery counter update (1:1 iOS `resolveAssistantDelivery` return). */
data class VoiceDeliveryOutcome(
    val shouldBeVoice: Boolean,
    val nextVoiceRoundsSinceLastVoice: Int,
)

/**
 * Decide whether this reply is voice (1:1 iOS `plannedAssistantDeliveryPlan`, minus side effects):
 * mirror a user voice message when a voice is available; otherwise go voice once the per-conversation
 * round counter reaches the (random) threshold. Pure → unit-testable; the random threshold itself is
 * generated by the caller and passed in.
 */
internal fun planAssistantDelivery(
    hasVoice: Boolean,
    latestUserMessageIsVoice: Boolean,
    voiceRoundsSinceLastVoice: Int,
    voiceNextThreshold: Int,
): AssistantDeliveryPlan {
    if (hasVoice && latestUserMessageIsVoice) {
        return AssistantDeliveryPlan(AssistantDeliveryMode.VOICE, AssistantDeliveryReason.USER_VOICE_MIRRORING)
    }
    val nextRound = voiceRoundsSinceLastVoice + 1
    val shouldBeVoice = nextRound >= voiceNextThreshold && hasVoice
    return if (shouldBeVoice) {
        AssistantDeliveryPlan(AssistantDeliveryMode.VOICE, AssistantDeliveryReason.SCHEDULED_VOICE)
    } else {
        AssistantDeliveryPlan(AssistantDeliveryMode.TEXT, AssistantDeliveryReason.TEXT)
    }
}

/**
 * Final voice/text decision + counter update (1:1 iOS `resolveAssistantDelivery`). Offline mode (or a
 * pending offline-meeting card) forces text and freezes the counter so a voice message doesn't fire
 * the instant offline mode ends; otherwise the counter increments, and resets to 0 when voice fires.
 */
internal fun resolveAssistantDelivery(
    isOffline: Boolean,
    hasOfflineMeetingAction: Boolean,
    plannedVoice: Boolean,
    voiceRoundsSinceLastVoice: Int,
): VoiceDeliveryOutcome {
    val shouldBeVoice = if (isOffline || hasOfflineMeetingAction) false else plannedVoice
    val roundsAfterThisReply = voiceRoundsSinceLastVoice + 1
    return when {
        shouldBeVoice -> VoiceDeliveryOutcome(true, 0)
        isOffline -> VoiceDeliveryOutcome(false, voiceRoundsSinceLastVoice)
        else -> VoiceDeliveryOutcome(false, roundsAfterThisReply)
    }
}

/** 本轮语音预判（对齐 iOS AssistantDeliveryPlan + MiniMaxVoiceTagsCapability + TTS 配置快照）。 */
internal data class VoicePlan(
    val plan: AssistantDeliveryPlan,
    val capability: MiniMaxVoiceTagsCapability,
    val config: TtsConfiguration?,
    val profile: TtsVoiceProfile,
    val apiKey: String,
    val roundsSinceLastVoice: Int,
    val threshold: Int,
)

/** 随机下一次语音回复轮次阈值（对齐 iOS nextVoiceReplyThreshold = Int.random(in: range)）。 */
internal fun nextVoiceReplyThreshold(settings: AppSettings): Int {
    val range = settings.sanitizedVoiceReplyRoundRange
    return Random.nextInt(range.first, range.last + 1)
}

/**
 * 计算本轮语音回复计划（对齐 iOS plannedAssistantDeliveryPlan + buildMiniMaxVoiceTagsCapability）：
 * 读 TTS 配置/角色音色 → hasVoice；首轮种下随机阈值；镜像用户语音消息或按轮次到阈值改投语音；
 * 并据此组装语气标签前门 capability（isVoiceMode = 本轮是否语音）。
 */
internal suspend fun resolveVoicePlan(
    character: CharacterEntity,
    convo: ConversationEntity,
    history: List<MessageEntity>,
    settings: AppSettings,
    conversationUuid: String,
    ttsConfigRepo: TtsConfigurationRepository,
    conversationRepo: ConversationRepository,
    appContext: Context,
): VoicePlan {
    val config = ttsConfigRepo.getConfiguration()
    val apiKey = ttsConfigRepo.getApiKey()
    val profile = TtsVoiceProfile(
        voiceIdentifier = character.voiceIdentifier,
        remoteVoiceID = character.remoteVoiceID,
        ttsEmotionRaw = character.ttsEmotionRaw,
        ttsSpeed = character.ttsSpeed,
        ttsPitch = character.ttsPitch,
    )
    val hasVoice = TtsService.hasAvailableVoice(profile, config, apiKey)
    // 首轮种下随机阈值（对齐 iOS voiceNextThreshold == 0 时 nextVoiceReplyThreshold）。
    val threshold = if (convo.voiceNextThreshold == 0) {
        nextVoiceReplyThreshold(settings).also {
            conversationRepo.updateVoiceRounds(conversationUuid, convo.voiceRoundsSinceLastVoice, it)
        }
    } else {
        convo.voiceNextThreshold
    }
    val latestUserVoice = history.lastOrNull { it.roleRaw == "user" }?.isVoiceMessage ?: false
    val plan = planAssistantDelivery(
        hasVoice = hasVoice,
        latestUserMessageIsVoice = latestUserVoice,
        voiceRoundsSinceLastVoice = convo.voiceRoundsSinceLastVoice,
        voiceNextThreshold = threshold,
    )
    val capability = MiniMaxVoiceTagsCapability(
        providerType = config.providerType,
        modelName = config.modelName,
        characterHasRemoteVoice = profile.remoteVoiceID.trim().isNotEmpty(),
        userToggleEnabled = MiniMaxVoiceTagsSettings.loadEnabled(appContext),
        isVoiceMode = plan.isVoice,
        isOfflineMode = convo.isInOfflineMode, // 线下沉浸时跳过语气标签注入（1:1 iOS）
    )
    return VoicePlan(plan, capability, config, profile, apiKey, convo.voiceRoundsSinceLastVoice, threshold)
}
