package com.situ.aichat.data.backup

import androidx.room.Room
import com.situ.aichat.data.local.AppDatabase
import com.situ.aichat.data.local.entity.MomentPostEntity
import com.situ.aichat.util.StringListJson
import kotlinx.coroutines.runBlocking
import kotlinx.serialization.json.Json
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.RuntimeEnvironment
import org.robolectric.annotation.Config

/**
 * T2-1（朋友圈发布页重构·甲 §7）：「提醒了谁」列的备份往返 + 老包兼容 + 恢复场景 D 的窗口查询（真 Room）。
 * 断言从图纸 §3.1 / K-5 / E18 / E19 独立反推（照 [PromiseBackupTest] 范式）。
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class MomentPostMentionBackupTest {

    private lateinit var db: AppDatabase
    private val json = Json { ignoreUnknownKeys = true; encodeDefaults = false }

    @Before fun setUp() {
        db = Room.inMemoryDatabaseBuilder(RuntimeEnvironment.getApplication(), AppDatabase::class.java)
            .allowMainThreadQueries()
            .build()
    }

    @After fun tearDown() { db.close() }

    private fun post(
        uuid: String,
        timestamp: Long,
        mentions: List<String> = emptyList(),
        author: String = "user",
        characterUuid: String? = null,
        softDeleted: Boolean = false,
    ) = MomentPostEntity(
        uuid = uuid,
        content = "内容$uuid",
        timestamp = timestamp,
        authorTypeRaw = author,
        characterUuid = characterUuid,
        isSoftDeleted = softDeleted,
        mentionedCharacterUuidsJson = StringListJson.encode(mentions),
    )

    /** a：带提醒的帖 toExport → JSON → toEntity("") 行级相等（除 imagePathsJson）。 */
    @Test
    fun a_带提醒的帖_往返行级相等() = runBlocking {
        val original = post("p1", 1_000L, mentions = listOf("c2", "c1")).copy(imagePathsJson = StringListJson.encode(listOf("/x.jpg")))
        db.momentDao().insertPost(original)
        val exported = db.momentDao().getPost("p1")!!.toExport(imageArchiveKeys = null)
        val decoded = json.decodeFromString(MomentPostExport.serializer(), json.encodeToString(MomentPostExport.serializer(), exported))
        val restored = decoded.toEntity(imagePathsJson = "")

        assertEquals(original.copy(imagePathsJson = ""), restored)
        assertEquals(StringListJson.encode(listOf("c2", "c1")), restored.mentionedCharacterUuidsJson)
    }

    /** a′：没提醒的帖导出不写该字段（null），再导入仍是 ""。 */
    @Test
    fun a2_没提醒的帖_导出不带字段_往返仍为空串() {
        val exported = post("p2", 2_000L).toExport(imageArchiveKeys = null)
        val text = json.encodeToString(MomentPostExport.serializer(), exported)
        assertFalse("没提醒 → 不写字段", text.contains("mentionedCharacterUuids"))
        val restored = json.decodeFromString(MomentPostExport.serializer(), text).toEntity(imagePathsJson = "")
        assertEquals("", restored.mentionedCharacterUuidsJson)
    }

    /** b：不含该字段的旧备份 JSON → toEntity 新列 = ""（E18·老包不崩）。 */
    @Test
    fun b_老备份无新字段_新列为空串() {
        val legacy = """{"uuid":"old1","content":"老帖","timestamp":123,"authorTypeRaw":"user","isAutoGenerated":false}"""
        val restored = json.decodeFromString(MomentPostExport.serializer(), legacy).toEntity(imagePathsJson = "")
        assertEquals("old1", restored.uuid)
        assertEquals("老帖", restored.content)
        assertEquals("", restored.mentionedCharacterUuidsJson)
    }

    /** c：恢复场景 D 查询只返回「用户帖 + 未软删 + 有提醒 + 窗口 (after, before) 内」，新→旧，LIMIT 生效。 */
    @Test
    fun c_场景D窗口查询_过滤排序与LIMIT() = runBlocking {
        val dao = db.momentDao()
        dao.insertPost(post("in1", 200L, mentions = listOf("c1")))
        dao.insertPost(post("in2", 300L, mentions = listOf("c2")))
        dao.insertPost(post("in3", 400L, mentions = listOf("c1", "c2")))
        dao.insertPost(post("noMention", 250L))
        dao.insertPost(post("deleted", 260L, mentions = listOf("c1"), softDeleted = true))
        dao.insertPost(post("aiPost", 270L, mentions = listOf("c1"), author = "character", characterUuid = "c9"))
        dao.insertPost(post("atAfter", 100L, mentions = listOf("c1")))
        dao.insertPost(post("atBefore", 500L, mentions = listOf("c1")))

        val all = dao.recentUserPostsWithMentionsInWindow(after = 100L, before = 500L, limit = 10)
        assertEquals(listOf("in3", "in2", "in1"), all.map { it.uuid })

        val limited = dao.recentUserPostsWithMentionsInWindow(after = 100L, before = 500L, limit = 2)
        assertEquals(listOf("in3", "in2"), limited.map { it.uuid })
    }
}
